version: '3.3'

services:
  db:
    image: postgres:11.4-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: mytestingdatabase
    tmpfs:
        - /var/cache